[tools]
rojo = "rojo-rbx/rojo@7.6.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.30.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
lune = "lune-org/lune@0.10.4"
