[package]
name = "nightcycle/simple-test"
description = "A lightweight test runner built for CI/CD actions"
version = "0.1.13"
license = "Apache"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]

[dependencies]
