[package]
name = "nightcycle/night-test"
description = "A test project for Nightcycle"
version = "0.1.0"
license = "Apache"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE"]

[dependencies]
